### ISSUE TITLE
Investment Shown Greater Than Invoice Amount

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#100]
Investor Login

I just notice that for invoice #41 which is closed, the "My Investment" shows amount of 1964, but the invoice is for 1000 and sales goal is 982.  As I remember you cannot input bidding amount greater that the invoice amount yet the amount invested shown is greater than the invoice amount.

![invoice41](https://user-images.githubusercontent.com/31194353/30098419-768f7f6c-9314-11e7-817c-2aec2e0f0040.png)

**Comment by makashtekar** [comment]
Causing because of 2 node instance running together and handling events each other separately. 
We are using one node instance so double record will not be saved further more :)
