### ISSUE TITLE
Investor login unable to see new invoice created by a borrower

### ISSUE THREAD

**Issue by rahrens1** [bitpopulous/alpha#16]
I created invoice #69 under user rthompson7905@gmail.com ( a borrower login).
Then logged in as an investor, user jscott7905@gmail.com but was unable to find invoice #69.

I'm guessing in the real app there would be some approval process to accept the new invoice before making it available to investors?

**Comment by makashtekar** [comment]
Exactly, Web master will have to approve before it ready for bidding :)
