### ISSUE TITLE
Reconciliation of Account Balance

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#24]
At the moment I can only see GBPPT balance which I think should be renamed as "GBP Pokens".  I am currently not able to reconcile the balance in my account.  I should be able to see the number of PPT in the account (those held as collateral and those not with balance to be the total PPT on Populous), The number of PPT used to buy Pokens and the rate for each purchase since the rate depends on the volatilty of trading.,

**Comment by zlatinov** [comment]
Duplicate with #45 #71
