### ISSUE TITLE
My Portfolio Page

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#28]
Is it my browser or settings used but I'm not getting the same crisp screen as presented in the medium post on 9 Aug for My Portfolio.  https://medium.com/bitpopulous/alpha-c68f5f2a00b5

This is what I'm getting:

![populousportfoliopagescreenshot](https://user-images.githubusercontent.com/31194353/29504186-73023bb0-8670-11e7-9943-1673d5611534.png)

I get same view when using Firefox and Chrome.

**Comment by BammBamm1988** [comment]
Yes, very light
