### ISSUE TITLE
Showstopper - User's are not recieving activation emails anymore

### ISSUE THREAD

**Issue by Nugg3t** [bitpopulous/alpha#4]
Many reports came through the chat that users were no longer receiving activation emails after creating their new accounts, on both investor and borrower side. Not sure if account activation requires two way Verification, if so this would make sense as to why users cannot login even though they have been verified on Admin Dashboard

**Comment by zlatinov** [comment]
Yes, accounts could be activated from the webmaster, only if their emails has been verified.

Now we changed this, so all newly registered accounts are automatically activated.
