### ISSUE TITLE
My Wallet - PPT Withdrawal

### ISSUE THREAD

**Issue by anthony-gerrits** [bitpopulous/alpha#40]
If you are a PPT token holder and you add PPT to the platform to use, how do you withdraw your tokens from the platform if you need to?

-  The My Wallet tab has the ability to Deposit PPT
- You can withdraw Pokens...

But there is no ability for PPT token holders to withdraw their PPT from the platform.

**Comment by zlatinov** [comment]
Reviewed in #71
