### ISSUE TITLE
Winning Bid Amount and Total Number of Bidders

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#57]
Investor Login - Invoice #6
1. Winner Bid group is A with winning bid amount of 545305 but summary shows winning bid amount as 7,600,000 the sales goal amount.
2. Click on "View Bids" - The total bids shown is "9" numbers and does not reconcile with the actual numbers of bidders, 20 in this case.

**Comment by makashtekar** [comment]
Duplicate #56
