### ISSUE TITLE
Reconcilation of Portfolio Data and Actual Amount Invested

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#58]
Investor Login
My portfolio data does not reconcile with the amount invested.  The investment shows amount of 551,618 but my investment amount only totals 3285.  Of the 3258 invested, only 1285 is successful amount invested.
An indication should be given of the invoices successfully bidded for, at the present monet I need to click "view' to see whether my invested amount is part of the winning group.

**Comment by makashtekar** [comment]
This was occurring before, we were using 2 node application, so for old invoices this might be an issue. 
Newer invoices should be fine.
