### ISSUE TITLE
Fatal Error on password recovery

### ISSUE THREAD

**Issue by Guest888** [bitpopulous/alpha#6]
(Brave Browser)

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 208 [FreeTDS][SQL Server]Invalid object name 'request_new_password'. (SQLExecute[208] at /builddir/build/BUILD/php-7.1.7/ext/pdo_odbc/odbc_stmt.c:260) in /var/www/html/config/class.database.php:119 Stack trace: #0 /var/www/html/config/class.database.php(119): PDOStatement->execute(Array) #1 /var/www/html/models/class.request_new_password.php(54): Database->prepare_execute('INSERT INTO req...', Array) #2 /var/www/html/forgot_password.php(44): RequestNewPassword->insert('32c9b88d175dfc7...', '1122', 'dispose@firstst...') #3 {main} thrown in /var/www/html/config/class.database.php on line 119

**Comment by makashtekar** [comment]
This has been fixed..
Created new table and separated password recovery for investor and borrower
