### ISSUE TITLE
Choose As Winner Group - But Not My Invoice

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#65]
Borrower Login

I go into marketplace to "buy" invoices, view bidding groups and once opened the button "Choose As Winner Group" is shown.  I press the button and the first time the transaction failed, then pressed a second time and this time the transaction was successful.  I did not even create this invoice yet I was able to terminate the auction of the invoice by choosing it as the winning group!

I then go into the second bidding group and do the same thing, I choose as winner and the transaction is successfully executed on the same invoice.

Suggest that if the invoice is not created by you, then the button "Choose As Winner Group" is not shown so that you are not able to terminate someone elses invoice auction.  Nevertheless the status of the invocie is still shown as "open".

**Comment by zlatinov** [comment]
Which invoice and which borrower account?

**Comment by PeterWong1** [comment]
I believe invoice #35 which I closed using my borrower account peterwongpopulous@gmail.com.

The invoice is now closed.

**Comment by makashtekar** [comment]
This has been fixed.. Checking invoice generator user as well
