### ISSUE TITLE
Penalties Received When Invoices Not Yet Due

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#67]
lnvestor Login

My receivables shows penalties of 9.82 but the invoices shown in my portfolio have not yet reached their due date.  The earliest "time left" is 4 days and 11 hours from now for invoice  #9.

**Comment by zlatinov** [comment]
The received payments are triggered manually from the webmaster panel. They happen when Populous has received the invoice amount from the borrower. 

Currently we're triggering the received payments earlier (manually from webmaster panel) for testing purposes, so it won't be matching the invoice due date.
