### ISSUE TITLE
Didn't receive verification email

### ISSUE THREAD

**Issue by rahrens1** [bitpopulous/alpha#7]
I've signed up for the alpha under investor I used jscott7905@gmail.com and for borrower as rthompson7905@gmail.com.  The signup seemed to go fine but it says I haven't been verified but haven't seen a verification email under either account.  I've checked inbox, promotions, and spam under gmail but no luck.  Any idea's why the verification didn't come thru?  Can you force verification so I can login on either side?  Unless you want to use this as a test for verification.   
FYI: I'm using a chrome browser.

Let me know next steps, thanks.

**Comment by zlatinov** [comment]
Sometimes verification emails are not being sent, we're looking into the issue.

Your account will be activated nonetheless. You can try to login now.

**Comment by makashtekar** [comment]
It working fine....
