### ISSUE TITLE
No Provision for PPT Withdrawal

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#71]
I can deposit PPT, deposit Pokens and withdrawal Pokens, but there is no provision for withdrawal of PPT unless "withdraw pokens" will also allow for withdrawal of PPT which is not yet included.

**Comment by zlatinov** [comment]
You can review your deposits with the Check Balance button. When you press it, a list of your balances is shown. Then you can click on each deposit, to release it. It will be successful, if you have enough Pokens to cover the value, you've received.

![image](https://user-images.githubusercontent.com/12032139/29702844-ab82c9a6-897b-11e7-9925-db8a6eaad125.png)
