### ISSUE TITLE
Populous Logo Overshadowed By The Red Notifcation Button

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#83]
I would also suggestion that the red notification button be placed elsewhere because the button overshadows the prominence of the Populous logo.  Maybe to place the red button on the right hand side of the screen.

Irrespective, the setting out of the red notification button differs in different views.

![notification01](https://user-images.githubusercontent.com/31194353/29815130-281c4118-8ce2-11e7-8fe4-58f7e09e8b8d.png)

![notification02](https://user-images.githubusercontent.com/31194353/29815146-35bd4f56-8ce2-11e7-9e3b-a8a2654db60d.png)

The text within the button is also not centralised.

**Comment by makashtekar** [comment]
This has been fixed 👍
