### ISSUE TITLE
Time Left on Invoices Incorrectly Shown

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/alpha#89]
Borrower Login

The due dates for invoices seem to be perennially fixed.  For example invoice #80 was created on 24 Aug 2017 with due date on 26 Aug 2017.  However the days left shows 6 days, 6 Hours left.  This was not noticed before but the number of days left appears to be incorrect since 26-24 is only 2 days.  Ideally the invoice should say time left has expired or words to that effect.

![dates01](https://user-images.githubusercontent.com/31194353/29958807-2259ff58-8f27-11e7-9cc5-6a65e11ca416.png)

Similarly invoices that have not been approved, invoice #92, also shows incorrect time for due dates.  The invoice was created on 27 Aug 2017 and with due date of 31 Aug 2017 (3  days) but the calculated time remaining shows 1 day, 6 hours.  Since the time has expired, the status should be expired even if not approved.

![dates02](https://user-images.githubusercontent.com/31194353/29958939-b2ec6af6-8f27-11e7-81c6-1e9434f984d3.png)

**Comment by makashtekar** [comment]
duplicate #92
